### ISSUE TITLE
SSL和SSB没看到有地方被调用

### ISSUE THREAD

**Issue by gongel** [Chongjie-Si/Subspace-Tuning#5]

**Comment by Chongjie-Si** [comment]
你好，感谢关注。SSL和SSB都在其对应的代码63行。
![1722334343423](https://github.com/user-attachments/assets/cb5e85b4-53fb-420a-aeea-91d0492ac6de)

**Comment by gongel** [comment]
我的意思是：有没有调用https://github.com/Chongjie-Si/Subspace-Tuning/blob/main/loralib/loralib/layers_SSL.py和layers_SSB.py这两个代码的example？没有svd对他初始化吗？

**Comment by Chongjie-Si** [comment]
你可以查看每个文件夹的README。仓库内没有直接对这两个代码的调用，不过你可以直接把 loralib中的layers.py文件替换成layers_SSL.py或者layers_SSB.py文件的内容，这样这些文件夹就是直接对这两个方法进行调用。具体调用的指令（以NLU为例）在https://github.com/Chongjie-Si/Subspace-Tuning/blob/main/NLU/src/transformers/models/deberta_v2/modeling_deberta_v2.py 294行以及其他地方可以看到。

SSL和SSB不需要SVD进行初始化。

**Comment by gongel** [comment]
好的，清楚了，多谢
